
- name: convert xml files to zip files
  hosts: all
  tasks:
    - name: execution of the archive module
      community.general.archive::
        path: /tmp/test/deal.xml
        dest: /tmp/test/deal.zip
        format: zip
